/* FM2 detailed franchise + player profiles */
function fm2Standing(abbr){ return db.standings.find(x=>x.team===abbr)||null; }
function fm2TeamGames(abbr,played=null){
  let gs=db.games.filter(g=>g.home===abbr||g.away===abbr);
  if(played===true)gs=gs.filter(g=>g.played);
  if(played===false)gs=gs.filter(g=>!g.played);
  return gs.sort((a,b)=>((a.stageIndex??0)-(b.stageIndex??0))||((a.weekIndex??0)-(b.weekIndex??0)));
}
function fm2Ordinal(n){ if(n==null)return '—'; const v=n%100; return n+(v>=11&&v<=13?'th':({1:'st',2:'nd',3:'rd'}[n%10]||'th')); }
function fm2Rank(p,key='ovr',scope=null){
  const ps=db.players.filter(x=>scope?scope(x):true).filter(x=>x?.[key]!=null).sort((a,b)=>(+b[key]||0)-(+a[key]||0));
  const i=ps.findIndex(x=>String(x.id)===String(p.id)); return i<0?null:i+1;
}
function fm2ValueRank(p,scope=null){
  const ps=db.players.filter(x=>scope?scope(x):true).sort((a,b)=>valueOf(b)-valueOf(a));
  const i=ps.findIndex(x=>String(x.id)===String(p.id)); return i<0?null:i+1;
}
function fm2RatingRows(p,group){
  const sets={
    athletic:[['Speed','speed'],['Acceleration','acceleration'],['Agility','agility'],['Strength','strength'],['Jumping','jumping'],['Stamina','stamina'],['Awareness','awareness'],['Toughness','toughness'],['Injury','injury']],
    receiving:[['Catching','catching'],['Catch in traffic','catchInTraffic'],['Spectacular catch','spectacularCatch'],['Release','release'],['Short route','shortRoute'],['Medium route','mediumRoute'],['Deep route','deepRoute']],
    rushing:[['Carrying','carrying'],['Break tackle','breakTackle'],['Trucking','trucking'],['Juke move','juke'],['Spin move','spin'],['Stiff arm','stiffArm'],['Ball carrier vision','bcVision']],
    passing:[['Throw power','throwPower'],['Short accuracy','shortAccuracy'],['Medium accuracy','mediumAccuracy'],['Deep accuracy','deepAccuracy'],['Throw on run','throwOnRun'],['Play action','playAction'],['Under pressure','underPressure'],['Break sack','breakSack']],
    defense:[['Tackle','tackle'],['Hit power','hitPower'],['Pursuit','pursuit'],['Play recognition','playRecognition'],['Man coverage','manCoverage'],['Zone coverage','zoneCoverage'],['Press','press'],['Block shedding','blockShedding'],['Power moves','powerMoves'],['Finesse moves','finesseMoves']],
    blocking:[['Pass block','passBlock'],['Run block','runBlock'],['Impact block','impactBlock'],['Pass block power','passBlockPower'],['Pass block finesse','passBlockFinesse'],['Run block power','runBlockPower'],['Run block finesse','runBlockFinesse'],['Lead block','leadBlock']],
    kicking:[['Kick power','kickPower'],['Kick accuracy','kickAccuracy']]
  };
  return (sets[group]||[]).map(([label,key])=>({label,value:p.ratings?.[key]})).filter(x=>x.value!=null);
}
function fm2RatingPanel(title,rows){
  if(!rows.length)return '';
  return '<div class="panel panel-pad rating-panel"><div class="kicker">'+esc(title)+'</div>'+rows.map(x=>'<div class="rating-row"><span>'+esc(x.label)+'</span><b>'+x.value+'</b><div class="rating-track"><i style="width:'+clamp(+x.value||0,0,99)+'%"></i></div></div>').join('')+'</div>';
}

renderTeamDetail=function(abbr){
  const t=team(abbr),m=rosterMetrics(abbr),rec=recordFor(abbr),rooms=roomMetrics(abbr),st=fm2Standing(abbr);
  const r=[...roster(abbr)].sort((a,b)=>(b.ovr||0)-(a.ovr||0));
  const contracts=[...r].filter(p=>p.capHit!=null).sort((a,b)=>(b.capHit||0)-(a.capHit||0));
  const expiring=r.filter(p=>+p.yearsLeft===1).sort((a,b)=>(b.ovr||0)-(a.ovr||0));
  const young=r.filter(p=>(+p.age||99)<=25).sort((a,b)=>valueOf(b)-valueOf(a));
  const top=r.slice(0,6), recent=fm2TeamGames(abbr,true).slice(-5).reverse(), upcoming=fm2TeamGames(abbr,false).slice(0,5);
  const pointDiff=st?.netPoints??((rec.pf??0)-(rec.pa??0));
  const totalCap=contracts.reduce((x,p)=>x+(+p.capHit||0),0);
  const ageBuckets=[['23 & under',r.filter(p=>(+p.age||99)<=23).length],['24–26',r.filter(p=>+p.age>=24&&+p.age<=26).length],['27–29',r.filter(p=>+p.age>=27&&+p.age<=29).length],['30+',r.filter(p=>+p.age>=30).length]];
  const seed=st?.seed!=null?'#'+st.seed+' seed':'Seed —', owner=st?.userName||t.userName||'—';
  const perf=[
    ['Points for',st?.pointsFor??rec.pf??'—',st?.pointsForRank?'#'+st.pointsForRank:''],
    ['Points against',st?.pointsAgainst??rec.pa??'—',st?.pointsAgainstRank?'#'+st.pointsAgainstRank:''],
    ['Total offense',st?.offTotalYds??'—',st?.offTotalYdsRank?'#'+st.offTotalYdsRank:''],
    ['Pass offense',st?.offPassYds??'—',st?.offPassYdsRank?'#'+st.offPassYdsRank:''],
    ['Rush offense',st?.offRushYds??'—',st?.offRushYdsRank?'#'+st.offRushYdsRank:''],
    ['Total defense',st?.defTotalYds??'—',st?.defTotalYdsRank?'#'+st.defTotalYdsRank:''],
    ['Pass defense',st?.defPassYds??'—',st?.defPassYdsRank?'#'+st.defPassYdsRank:''],
    ['Rush defense',st?.defRushYds??'—',st?.defRushYdsRank?'#'+st.defRushYdsRank:''],
    ['Turnover diff',st?.turnoverDiff??'—',''],['Streak',st?.streak??'—','']
  ];
  return pageHead(t.city+' '+t.name,(rec.w+'-'+rec.l+(rec.t?'-'+rec.t:''))+' · '+t.division+' · '+rosterProfile(abbr),'<button class="btn" data-go="teams">← All teams</button>')+
  '<section class="team-hq" style="--c1:'+esc(t.c1)+';--c2:'+esc(t.c2)+'"><div class="team-hq-copy"><div class="eyebrow">'+abbr+' FRANCHISE HQ · '+esc(seed)+'</div><h1>'+esc(t.city)+' '+esc(t.name)+'</h1><p>'+m.count+' players · '+m.xf+' X-Factors · '+m.ss+' Superstars · '+m.star+' Stars · Owner '+esc(owner)+'</p><div class="team-hq-chips"><span>'+rec.w+'-'+rec.l+(rec.t?'-'+rec.t:'')+'</span><span>'+esc(t.division||'')+'</span><span>'+esc(rosterProfile(abbr))+'</span>'+(st?.playoffStatus?'<span>'+esc(st.playoffStatus)+'</span>':'')+'</div></div><div class="team-hq-logo">'+teamImg(abbr,'team-detail-logo')+'</div></section>'+
  '<section class="section"><div class="grid stats">'+statCard('Team OVR',t.overall??st?.teamOvr??(m.top22Ovr?m.top22Ovr.toFixed(1):'—'),'NeonSportz / roster view')+statCard('Power model',m.power,'FM2 Hub roster model')+statCard('Point differential',pointDiff>0?'+'+pointDiff:pointDiff,'PF '+(st?.pointsFor??rec.pf??'—')+' · PA '+(st?.pointsAgainst??rec.pa??'—'))+statCard('Cap available',fmtM(t.capAvailable),'Cap used '+fmtM(t.capSpent))+'</div></section>'+
  '<section class="section grid cols-2"><div class="panel panel-pad"><div class="section-head"><div><div class="kicker">Season profile</div><h2>Team performance</h2></div></div><div class="profile-grid">'+perf.map(([label,val,rank])=>'<div class="profile-stat"><span>'+esc(label)+'</span><b>'+esc(val)+'</b><small>'+esc(rank)+'</small></div>').join('')+'</div></div><div class="panel panel-pad"><div class="section-head"><div><div class="kicker">Roster makeup</div><h2>Construction</h2></div></div><div class="row"><b>Average age</b><span>'+(m.avgAge?m.avgAge.toFixed(1):'—')+'</span></div><div class="row"><b>Age 25 or younger</b><span>'+m.youngCount+'</span></div><div class="row"><b>Expiring contracts</b><span>'+expiring.length+'</span></div><div class="row"><b>Listed cap hits</b><span>'+fmtM(totalCap)+'</span></div><div class="row"><b>Roster value</b><span>'+fmtN(Math.round(m.rosterValue))+'</span></div><div class="age-buckets">'+ageBuckets.map(([l,n])=>'<div><b>'+n+'</b><span>'+l+'</span></div>').join('')+'</div></div></section>'+
  '<section class="section"><div class="section-head"><div><div class="kicker">Star power</div><h2>Top players</h2></div></div><div class="grid cols-3">'+top.map((p,i)=>'<div class="feature-player clickable" data-player="'+esc(p.id)+'"><div class="feature-player-top"><span class="feature-rank">'+(i+1)+'</span>'+playerImg(p,'feature-avatar')+'<div><div class="person-name">'+esc(p.name)+'</div><div class="minor">'+p.pos+' · Age '+(p.age??'—')+' · '+fmtM(p.capHit)+'</div></div><span class="feature-ovr">'+(p.ovr??'—')+'</span></div><div class="feature-foot">'+devBadge(p.dev)+'<span>Value '+fmtN(valueOf(p))+'</span></div></div>').join('')+'</div></section>'+
  '<section class="section"><div class="section-head"><div><div class="kicker">Roster strength map</div><h2>Position rooms</h2></div></div><div class="room-grid">'+Object.entries(rooms).map(([g,x])=>'<div class="room"><div class="kicker">'+g+'</div><b>'+(x.score?x.score.toFixed(1):'—')+'</b><small>'+(x.players.slice(0,3).map(p=>p.name).join(' · ')||'No players')+'</small><div class="bar"><i style="width:'+clamp(((x.score||60)-60)/40*100,0,100)+'%"></i></div></div>').join('')+'</div></section>'+
  '<section class="section split"><div><div class="section-head"><div><div class="kicker">Full roster</div><h2>'+r.length+' players</h2></div></div>'+table([{label:'Player'},{label:'OVR'},{label:'Dev'},{label:'SPD'},{label:'Cap'},{label:'Value'}],r.map(p=>playerRow(p)).join(''))+'</div><div><div class="section-head"><div><div class="kicker">Cap war room</div><h2>Largest cap hits</h2></div></div><div class="panel">'+contracts.slice(0,8).map((p,i)=>'<div class="rank-card clickable" data-player="'+esc(p.id)+'"><div class="rank-num">'+(i+1)+'</div>'+playerImg(p)+'<div><div class="person-name">'+esc(p.name)+'</div><div class="minor">'+p.pos+' · '+(p.yearsLeft??'—')+' yrs left · '+(p.ovr??'—')+' OVR</div></div><div class="rank-score">'+fmtM(p.capHit)+'<small>CAP</small></div></div>').join('')+'</div><div class="section-head" style="margin-top:16px"><div><div class="kicker">Young core</div><h2>Best age-25-and-under assets</h2></div></div><div class="panel">'+(young.slice(0,6).map((p,i)=>'<div class="rank-card clickable" data-player="'+esc(p.id)+'"><div class="rank-num">'+(i+1)+'</div>'+playerImg(p)+'<div><div class="person-name">'+esc(p.name)+'</div><div class="minor">'+p.pos+' · Age '+(p.age??'—')+' · '+esc(p.dev||'Normal')+'</div></div><div class="rank-score">'+fmtN(valueOf(p))+'<small>VALUE</small></div></div>').join('')||empty('No qualifying players.'))+'</div></div></section>'+
  '<section class="section grid cols-2">'+gamePanel('Recent results',recent)+gamePanel('Upcoming games',upcoming)+'</section>';
};

renderPlayerDetail=function(id){
  const p=db.players.find(x=>String(x.id)===String(id)); if(!p)return empty('Player not found.');
  const t=team(p.team),prev=previousSnapshot?.players?.[String(p.id)],deltas=[];
  if(prev){if(prev.ovr!==p.ovr)deltas.push('OVR '+prev.ovr+' → '+p.ovr);if(prev.team!==p.team)deltas.push('Team '+prev.team+' → '+p.team);if(prev.dev!==p.dev)deltas.push('Dev '+prev.dev+' → '+p.dev);if(prev.value!==p.value)deltas.push('Value '+fmtN(prev.value)+' → '+fmtN(p.value));}
  const leagueOvr=fm2Rank(p,'ovr'),posOvr=fm2Rank(p,'ovr',x=>x.pos===p.pos),teamOvr=fm2Rank(p,'ovr',x=>x.team===p.team),valueRank=fm2ValueRank(p),posValue=fm2ValueRank(p,x=>x.pos===p.pos);
  const peers=roster(p.team).filter(x=>x.pos===p.pos&&String(x.id)!==String(p.id)).sort((a,b)=>(b.ovr||0)-(a.ovr||0)).slice(0,5), panels=[];
  const add=(title,key)=>{const rows=fm2RatingRows(p,key);if(rows.length)panels.push(fm2RatingPanel(title,rows));}; add('Athletic profile','athletic');
  if(p.pos==='QB')add('Passing','passing'); if(['HB','FB'].includes(p.pos))add('Ball carrier','rushing'); if(['WR','TE','HB'].includes(p.pos))add('Receiving','receiving'); if(['LT','LG','C','RG','RT','TE','FB'].includes(p.pos))add('Blocking','blocking'); if(['LE','RE','DT','LOLB','MLB','ROLB','CB','FS','SS'].includes(p.pos))add('Defense','defense'); if(['K','P'].includes(p.pos))add('Kicking','kicking');
  const tg=fm2TeamGames(p.team,true).slice(-4).reverse(), rec=recordFor(p.team);
  return pageHead(p.name,p.team+' · '+p.pos+' · Age '+(p.age??'—')+' · '+(p.dev||'Normal'),'<button class="btn" data-go="players">← Player database</button>')+
  '<section class="player-hero" style="--c1:'+esc(t.c1)+';--c2:'+esc(t.c2)+'"><div class="player-visual" style="--c1:'+esc(t.c1)+';--c2:'+esc(t.c2)+'">'+(p.headshot?'<img src="'+esc(p.headshot)+'" onerror="this.style.display=\'none\'">':'<div class="fallback-head">'+esc((p.name||'?').split(/\s+/).map(x=>x[0]).slice(0,2).join(''))+'</div>')+'</div><div class="player-info"><div class="eyebrow">'+p.team+' '+p.pos+(p.jersey!=null?' · #'+p.jersey:'')+'</div><h1>'+esc(p.name)+'</h1><div class="player-meta"><span class="ovr-badge">'+(p.ovr??'—')+' OVR</span>'+devBadge(p.dev)+'<span class="tag">Age '+(p.age??'—')+'</span><span class="tag">'+(p.yearsPro??'—')+' yrs pro</span>'+(p.archetype?'<span class="tag">'+esc(p.archetype)+'</span>':'')+(p.tradeBlock?'<span class="tag warn">Trade block flag in source</span>':'')+'</div><div class="metric-row"><div class="metric-box"><b>'+(p.speed??'—')+'</b><span>Speed</span></div><div class="metric-box"><b>'+fmtN(valueOf(p))+'</b><span>Trade value</span></div><div class="metric-box"><b>'+fmtM(p.capHit)+'</b><span>Cap hit</span></div><div class="metric-box"><b>'+(p.yearsLeft??'—')+'</b><span>Years left</span></div></div><div class="hero-actions"><button class="btn" data-team="'+p.team+'">Open '+p.team+'</button><button class="btn primary" data-add-trade="'+esc(p.id)+'">Add to Trade Lab</button><a class="btn link" href="https://neonsportz.com/leagues/FM2/players/'+encodeURIComponent(p.pageId||p.id)+'" target="_blank" rel="noopener">Open NeonSportz</a></div></div></section>'+
  '<section class="section"><div class="grid stats">'+statCard('League OVR rank',fm2Ordinal(leagueOvr),(p.ovr??'—')+' OVR')+statCard(p.pos+' OVR rank',fm2Ordinal(posOvr),'Among '+p.pos+'s')+statCard('League value rank',fm2Ordinal(valueRank),fmtN(valueOf(p))+' value')+statCard('Team OVR rank',fm2Ordinal(teamOvr),p.team+' roster')+'</div></section>'+
  '<section class="section grid cols-3"><div class="panel panel-pad"><div class="kicker">Player identity</div><div class="row"><b>Jersey</b><span>'+(p.jersey!=null?'#'+p.jersey:'—')+'</span></div><div class="row"><b>Height</b><span>'+esc(p.height??'—')+'</span></div><div class="row"><b>Weight</b><span>'+(p.weight??'—')+'</span></div><div class="row"><b>College</b><span>'+esc(p.college??'—')+'</span></div><div class="row"><b>Draft</b><span>'+(p.draftRound?'Round '+p.draftRound+' · Pick '+(p.draftPick??'—'):'—')+'</span></div><div class="row"><b>Rookie year</b><span>'+(p.rookieYear??'—')+'</span></div></div><div class="panel panel-pad"><div class="kicker">Contract</div><div class="row"><b>Current cap hit</b><span>'+fmtM(p.capHit)+'</span></div><div class="row"><b>Contract salary</b><span>'+fmtM(p.contractSalary)+'</span></div><div class="row"><b>Signing bonus</b><span>'+fmtM(p.contractBonus)+'</span></div><div class="row"><b>Length</b><span>'+(p.contractLength??'—')+' yrs</span></div><div class="row"><b>Years remaining</b><span>'+(p.yearsLeft??'—')+'</span></div><div class="row"><b>Release savings</b><span>'+fmtM(p.net)+'</span></div><div class="row"><b>Release penalty</b><span>'+fmtM(p.releasePenaltyTotal)+'</span></div><div class="row"><b>Trade-in cap est.</b><span>'+fmtM(p.tradeInCap)+'</span></div></div><div class="panel panel-pad"><div class="kicker">FM2 standing</div><div class="row"><b>Position value rank</b><span>'+fm2Ordinal(posValue)+'</span></div><div class="row"><b>Development</b><span>'+esc(p.dev||'Normal')+'</span></div><div class="row"><b>Team</b><span>'+p.team+' · '+esc(t.name)+'</span></div><div class="row"><b>Team power</b><span>'+rosterMetrics(p.team).power+'</span></div><div class="row"><b>Team record</b><span>'+rec.w+'-'+rec.l+(rec.t?'-'+rec.t:'')+'</span></div><div class="row"><b>Source ID</b><span>'+esc(p.pageId||p.id)+'</span></div></div></section>'+
  (panels.length?'<section class="section"><div class="section-head"><div><div class="kicker">Scouting profile</div><h2>Madden ratings</h2></div><div class="hint">Only ratings present in the FM2 feed are shown.</div></div><div class="grid cols-3">'+panels.join('')+'</div></section>':'')+
  '<section class="section grid cols-2"><div><div class="section-head"><div><div class="kicker">Position room</div><h2>'+p.team+' '+p.pos+'s</h2></div></div><div class="panel"><div class="rank-card clickable" data-player="'+esc(p.id)+'"><div class="rank-num">★</div>'+playerImg(p)+'<div><div class="person-name">'+esc(p.name)+'</div><div class="minor">Current player · '+esc(p.dev||'Normal')+'</div></div><div class="rank-score">'+(p.ovr??'—')+'<small>OVR</small></div></div>'+peers.map((x,i)=>'<div class="rank-card clickable" data-player="'+esc(x.id)+'"><div class="rank-num">'+(i+2)+'</div>'+playerImg(x)+'<div><div class="person-name">'+esc(x.name)+'</div><div class="minor">'+(x.age??'—')+' yrs · '+esc(x.dev||'Normal')+'</div></div><div class="rank-score">'+(x.ovr??'—')+'<small>OVR</small></div></div>').join('')+'</div></div><div><div class="section-head"><div><div class="kicker">Change tracker</div><h2>Since your previous visit</h2></div></div><div class="panel panel-pad">'+(deltas.length?deltas.map(x=>'<div class="flag">'+esc(x)+'</div>').join(''):'<p class="hint">No OVR, team, development-trait or value change detected since the previous snapshot stored in this browser.</p>')+'</div>'+(tg.length?'<div class="section-head" style="margin-top:16px"><div><div class="kicker">Team context</div><h2>Recent '+p.team+' results</h2></div></div><div class="panel">'+tg.map(gameCard).join('')+'</div>':'')+'</div></section>';
};
if(typeof render==='function' && db?.players?.length) render();
